FROM ubuntu:20.04

ENV TZ=Europe/Kiev

COPY . /

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone && \
    cd /debian-setup/ && bash ./install.sh && \
    # remove autogenerated .zshrc file
    rm ~/.zshrc && \
    # install configuration files
    cd /.dotfiles && bash ./install.sh && \
    # create files to store env vars and aliases
    # they are sourced in .zshrc file
    touch ~/.config/env_variables.bash && \
    touch ~/.config/aliases.bash

CMD ["zsh"]
