version: 2.1

# workflows:
#   version: 2
#   build-master:
#     jobs:
#       - build:
#           filters:
#             branches:
#               only: main

jobs:
  build:
    environment:
      IMAGE_NAME: arthuryatsun/dev-setup
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build